version: '3.8'

services:

    db:
        container_name: pg_container
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: dbpass
            POSTGRES_DB: admin
        ports:
            - "5432:5432"

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - db
        links:
            - db

    app:
        build: .
        depends_on: 
            - adminer
        links:
            - db
        environment: 
            USERNAME: admin
            PASSWORD: dbpass
            SERVER_IP: db
            DATABASE_NAME: admin
            TZ: "America/New_York"
        command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        ports:
            - 8000:8000
        



